INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("project 1", "category 1", 10, "Oct 1", "Oct 30");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("project 2", "category 2", 20, "Nov 1", "Nov 30");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("project 3", "category 3", 40, "Dec 1", "Dec 30");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("project 4", "category 4", 80, "Jan 1", "Jan 30");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("project 5", "category 5", 160, "Oct 1", "Oct 30");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("project 6", "category 1", 320, "Nov 1", "Nov 30");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("project 7", "category 2", 100, "Dec 1", "Dec 30");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("project 8", "category 3", 200, "Jan 1", "Jan 30");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("project 9", "category 4", 300, "Feb 1", "Feb 30");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("project 10", "category 5", 400, "Mar 1", "Mar 30");

INSERT INTO users (name, age) VALUES ("Yassi", 24);
INSERT INTO users (name, age) VALUES ("Bennie", 17);
INSERT INTO users (name, age) VALUES ("Ayis", 28);
INSERT INTO users (name, age) VALUES ("Rick", 54);
INSERT INTO users (name, age) VALUES ("Sharon", 56);
INSERT INTO users (name, age) VALUES ("Niovi", 17);
INSERT INTO users (name, age) VALUES ("Hannah", 24);
INSERT INTO users (name, age) VALUES ("America", 26);
INSERT INTO users (name, age) VALUES ("Amanda", 25);
INSERT INTO users (name, age) VALUES ("Claire", 56);
INSERT INTO users (name, age) VALUES ("Constantine", 56);
INSERT INTO users (name, age) VALUES ("Iris", 24);
INSERT INTO users (name, age) VALUES ("Austin", 23);
INSERT INTO users (name, age) VALUES ("Tabbie", 59);
INSERT INTO users (name, age) VALUES ("Ponta", 25);
INSERT INTO users (name, age) VALUES ("Cheyonne", 22);
INSERT INTO users (name, age) VALUES ("Liam", 28);
INSERT INTO users (name, age) VALUES ("Jordan", 33);
INSERT INTO users (name, age) VALUES ("Genevieve", 27);
INSERT INTO users (name, age) VALUES ("Costa", 30);

INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (60, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (70, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (80, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (90, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 10, 0);
INSERT INTO pledges (amount, user_id, project_id) VALUES (110, 11, 11);
INSERT INTO pledges (amount, user_id, project_id) VALUES (120, 12, 12);
INSERT INTO pledges (amount, user_id, project_id) VALUES (130, 13, 13);
INSERT INTO pledges (amount, user_id, project_id) VALUES (140, 14, 14);
INSERT INTO pledges (amount, user_id, project_id) VALUES (150, 15, 15);
INSERT INTO pledges (amount, user_id, project_id) VALUES (160, 16, 16);
INSERT INTO pledges (amount, user_id, project_id) VALUES (170, 17, 17);
INSERT INTO pledges (amount, user_id, project_id) VALUES (180, 18, 18);
INSERT INTO pledges (amount, user_id, project_id) VALUES (190, 19, 19);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 20);
INSERT INTO pledges (amount, user_id, project_id) VALUES (210, 21, 21);
INSERT INTO pledges (amount, user_id, project_id) VALUES (220, 22, 22);
INSERT INTO pledges (amount, user_id, project_id) VALUES (230, 23, 23);
INSERT INTO pledges (amount, user_id, project_id) VALUES (240, 24, 24);
INSERT INTO pledges (amount, user_id, project_id) VALUES (250, 25, 25);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260, 26, 26);
INSERT INTO pledges (amount, user_id, project_id) VALUES (270, 27, 27);
INSERT INTO pledges (amount, user_id, project_id) VALUES (280, 28, 28);
INSERT INTO pledges (amount, user_id, project_id) VALUES (290, 29, 29);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 30, 30);
