INSERT INTO users (name, age) VALUES ("Shirley", 22);
INSERT INTO users (name, age) VALUES ("Kelly", 19);
INSERT INTO users (name, age) VALUES ("Will", 25);
INSERT INTO users (name, age) VALUES ("Polly", 15);
INSERT INTO users (name, age) VALUES ("Bob", 45);
INSERT INTO users (name, age) VALUES ("Ash", 30);
INSERT INTO users (name, age) VALUES ("May", 15);
INSERT INTO users (name, age) VALUES ("Sheryl", 69);
INSERT INTO users (name, age) VALUES ("Kevin", 15);
INSERT INTO users (name, age) VALUES ("Michelle", 26);
INSERT INTO users (name, age) VALUES ("A", 46);
INSERT INTO users (name, age) VALUES ("B", 21);
INSERT INTO users (name, age) VALUES ("C", 73);
INSERT INTO users (name, age) VALUES ("D", 13);
INSERT INTO users (name, age) VALUES ("E", 35);
INSERT INTO users (name, age) VALUES ("F", 25);
INSERT INTO users (name, age) VALUES ("G", 19);
INSERT INTO users (name, age) VALUES ("H", 52);
INSERT INTO users (name, age) VALUES ("I", 26);
INSERT INTO users (name, age) VALUES ("J", 41);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Boat", "Personal", 5000, "Jan-1", "Feb-1");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Earth", "Enviromental", 20000, "Jan-1", "Feb-1");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Libraries", "Books", 3000, "Jan-1", "Feb-1");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Guitar", "Music", 2000, "Jan-1", "Feb-1");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("School Program", "Music", 50000, "Jan-1", "Feb-1");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Children Enrichment", "Books", 10000, "Jan-1", "Feb-1");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Red Rising", "Books", 500, "Jan-1", "Feb-1");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Save the Earth", "Enviromental", 100000, "Jan-1", "Feb-1");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Plastic Surgery", "Personal", 5000, "Jan-1", "Feb-1");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Choir", "Music", 800, "Jan-1", "Feb-1");

INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 12, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (226, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (140, 8, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800, 17, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 4, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 11, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 18, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 15, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 9, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 12, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 7, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 20, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 17, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 13, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 11, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 15, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 16, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 6, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 16, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 8, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 2, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 16, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 16, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 9, 10);
