INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project 1', 'startup', 250000, 120117, 32018);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project 2', 'startup', 250000, 120117, 32018);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project 3', 'startup', 250000, 120117, 32018);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project 4', 'startup', 250000, 120117, 32018);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project 5', 'startup', 250000, 120117, 32018);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project 6', 'startup', 250000, 120117, 32018);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project 7', 'startup', 250000, 120117, 32018);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project 8', 'startup', 250000, 120117, 32018);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project 9', 'startup', 250000, 120117, 32018);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project 10', 'startup', 250000, 120117, 32018);
INSERT INTO users (name, age) VALUES ('Dave', 40);
INSERT INTO users (name, age) VALUES ('Tim', 30);
INSERT INTO users (name, age) VALUES ('Jill', 34);
INSERT INTO users (name, age) VALUES ('Brenda', 59);
INSERT INTO users (name, age) VALUES ('Herb', 45);
INSERT INTO users (name, age) VALUES ('Burt', 28);
INSERT INTO users (name, age) VALUES ('Anne', 23);
INSERT INTO users (name, age) VALUES ('Joe', 40);
INSERT INTO users (name, age) VALUES ('Steve', 29);
INSERT INTO users (name, age) VALUES ('Tara', 42);
INSERT INTO users (name, age) VALUES ('Jim', 39);
INSERT INTO users (name, age) VALUES ('Pete', 35);
INSERT INTO users (name, age) VALUES ('Christie', 20);
INSERT INTO users (name, age) VALUES ('Jack', 62);
INSERT INTO users (name, age) VALUES ('Paul', 33);
INSERT INTO users (name, age) VALUES ('Melissa', 31);
INSERT INTO users (name, age) VALUES ('Sandra', 50);
INSERT INTO users (name, age) VALUES ('Hope', 39);
INSERT INTO users (name, age) VALUES ('Bill', 19);
INSERT INTO users (name, age) VALUES ('Ted', 19);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 3, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2500, 8, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4000, 1, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 18, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000, 2, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800, 4, 17);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 15, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 5, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 6, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (700, 11, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 13, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 9, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (900, 14, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (550, 17, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (350, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 5, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 1, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 2, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 3, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 4, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 10, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 13, 6);
